name: CI

on: push

jobs:
  deps:
    name: Setup and get deps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      
      - name: Install dependencies
        run: npm ci
  
      - name: Check types
        run: npm exec tsc

      - name: Run ESLint
        run: npm run lint

      - name: Compile
        run:
          npm run build

      - name: Check tests
        run: npm run test

      - name: Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec electron-builder build --publish=never

      - if: matrix.os == 'ubuntu-latest'
        name: Ubuntu release
        uses: actions/upload-artifact@v3
        with:
          name: Linux AppImage
          path: release/build/BonBon-*.*.*.AppImage
      - if: matrix.os == 'macos-latest'
        name: MacOS release
        uses: actions/upload-artifact@v3
        with:
          name: MacOS build
          path: |
            release/build/BonBon-*.*.*-arm64.dmg
            release/build/BonBon-*.*.*.dmg
      - if: matrix.os == 'windows-latest'
        name: Windows release
        uses: actions/upload-artifact@v3
        with:
          name: Windows exe
          path: release/build/BonBon Setup *.*.*.exe