name: CI

on: push

jobs:
  deps:
    name: Setup and get deps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm exec tsc

      - name: Run ESLint
        run: npm run lint

      - name: Compile
        run:
          npm run build

      - name: Check tests
        run: npm run test
