name: Package

on: push

jobs:
  deps:
    name: Setup and get deps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run build

      - name: Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec electron-builder build --publish=never

      - if: matrix.os == 'ubuntu-latest'
        name: Ubuntu release
        uses: actions/upload-artifact@v3
        with:
          name: BonBon-linux
          path: |
            release/build/*-latest.yml
            release/build/BonBon-*.*.*.AppImage
      - if: matrix.os == 'macos-latest'
        name: MacOS release
        uses: actions/upload-artifact@v3
        with:
          name: BonBon-macos
          path: |
            release/build/*-latest.yml
            release/build/BonBon-*.*.*-arm64.dmg
            release/build/BonBon-*.*.*.dmg
      - if: matrix.os == 'windows-latest'
        name: Windows release
        uses: actions/upload-artifact@v3
        with:
          name: BonBon-windows
          path: |
            release/build/*-latest.yml
            release/build/BonBon Setup *.*.*.exe
