name: Package

on: push

jobs:
  deps:
    name: Setup, Test, and Package
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: install ts-node for everyone
        run: npm install -g ts-node husky

      - name: Install dependencies
        run: |
          npm ci --omit=dev --legacy-peer-deps

      - name: Compile
        run: |
          npm run build

      - name: Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder build --publish=never

      # Ubuntu packaging and testing for Snap, Flatpak, Tarball, AppImage, DEB, and RPM
      - if: matrix.os == 'ubuntu-latest'
        name: Build Snap, Flatpak, Tarball, AppImage, DEB, and RPM
        run: |
          sudo apt-get update
          sudo apt-get install -y snapcraft flatpak flatpak-builder
          npm exec electron-builder --linux snap flatpak tar.gz appimage deb rpm

      - if: matrix.os == 'ubuntu-latest'
        name: Ubuntu artifacts upload
        uses: actions/upload-artifact@v4
        with:
          name: BonBon-linux
          path: |
            release/build/*-latest.yml
            release/build/BonBon-*.*.*.snap
            release/build/BonBon-*.*.*.flatpak
            release/build/BonBon-*.*.*.tar.gz
            release/build/BonBon-*.*.*.AppImage
            release/build/BonBon-*.*.*.deb
            release/build/BonBon-*.*.*.rpm

      # MacOS packaging and testing for DMG
      - if: matrix.os == 'macos-latest'
        name: Build DMG
        run: |
          npm exec electron-builder --mac dmg

      - if: matrix.os == 'macos-latest'
        name: MacOS artifacts upload
        uses: actions/upload-artifact@v4
        with:
          name: BonBon-macos
          path: |
            release/build/*-latest.yml
            release/build/BonBon-*.*.*-arm64.dmg
            release/build/BonBon-*.*.*.dmg

      # Windows packaging and testing for EXE and Portable
      - if: matrix.os == 'windows-latest'
        name: Build EXE and Portable
        run: |
          npm exec electron-builder --win nsis portable

      - if: matrix.os == 'windows-latest'
        name: Windows artifacts upload
        uses: actions/upload-artifact@v4
        with:
          name: BonBon-windows
          path: |
            release/build/*-latest.yml
            release/build/BonBon Setup *.*.*.exe
            release/build/BonBon-*.*.*.exe
