name: Release latest

on:
  push:
    branches:
      - 'develop'
      - 'release-ci'

jobs:
  publish_on_windows:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@master

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm exec tsc

      - name: Run ESLint
        run: npm run lint

      - name: Compile
        run: npm run build

      - name: Check tests
        run: npm run test

      - name: Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec electron-builder build

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest
          files: |
            release/build/BonBon *.*.* Setup.exe

  publish_on_macos:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@master

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm exec tsc

      - name: Run ESLint
        run: npm run lint

      - name: Compile
        run: npm run build

      - name: Check tests
        run: npm run test

      - name: Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec electron-builder build

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest
          files: |
            release/build/BonBon-*.*.*-arm64.dmg
            release/build/BonBon-*.*.*.dmg

  publish_on_linux:
    runs-on: linux-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@master

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm exec tsc

      - name: Run ESLint
        run: npm run lint

      - name: Compile
        run: npm run build

      - name: Check tests
        run: npm run test

      - name: Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec electron-builder build

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest
          files: |
            release/build/BonBon-*.*.*.AppImage
