name: Release unstable

on:
  push:
    branches:
      - 'main'
      - 'release-ci'

jobs:
  deps:
    name: Setup and get deps
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm exec tsc

      - name: Run ESLint
        run: npm run lint

      - name: Compile
        run: npm run build

      - name: Check tests
        run: npm run test

      - name: Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec electron-builder build --publish=never

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: unstable-upstream
          prerelease: true
          title: Unstable upstream release
          files: |
            release/build/BonBon-*.*.*-arm64.dmg
            release/build/BonBon-*.*.*.dmg
            release/build/BonBon-*.*.*.AppImage
            release/build/BonBon *.*.* Setup.exe
