name: Release

on:
  release:
    types:
      - created

jobs:
  checkVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Get dependencies
        run: pip3 install semver

      # - name: Compare tag version and internal version
      #   env:
      #     TAG: ${{ github.ref }}
      #   run: python3 ./.github/compare_versions.py

  release:
    # needs: checkVersions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # - name: Check types
      #   run: npm exec tsc

      # - name: Run ESLint
      #   run: npm run lint

      - name: Compile
        run: npm run build

      # - name: Check tests
      #   run: npm run test

      - name: Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec electron-builder build --publish=never

      - name: Enhanced logging for macOS notarization
        if: matrix.os == 'macos-latest'
        run: |
          set -e
          xcrun altool --notarize-app --primary-bundle-id "org.erb.BonBon" --username "$APPLE_ID" --password "$APPLE_ID_PASSWORD" --file release/build/BonBon-*.*.*.dmg | tee notarization_log.txt
          xcrun stapler staple release/build/BonBon-*.*.*.dmg | tee -a notarization_log.txt

      - name: Verify macOS notarization
        if: matrix.os == 'macos-latest'
        run: xcrun stapler validate release/build/BonBon-*.*.*.dmg

      - if: matrix.os == 'ubuntu-latest'
        name: Linux Appimage release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file_glob: true
          file: release/build/*-latest.yml
          tag: ${{ github.ref }}

      - if: matrix.os == 'ubuntu-latest'
        name: Linux Appimage release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file_glob: true
          file: release/build/BonBon-*.*.*.AppImage
          tag: ${{ github.ref }}

      - if: matrix.os == 'macos-latest'
        name: macOS arm64 release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file_glob: true
          file: release/build/BonBon-*.*.*-arm64.dmg
          tag: ${{ github.ref }}

      - if: matrix.os == 'macos-latest'
        name: macOS intel release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file_glob: true
          file: release/build/BonBon-*.*.*.dmg
          tag: ${{ github.ref }}

      - if: matrix.os == 'macos-latest'
        name: latest.yml release for macOS
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file_glob: true
          file: release/build/*-latest.yml
          tag: ${{ github.ref }}

      - name: Notarize app (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          set -e
          xcrun altool --notarize-app --primary-bundle-id "org.erb.BonBon" --username "$APPLE_ID" --password "$APPLE_ID_PASSWORD" --file release/build/BonBon-*.*.*.dmg | tee notarization_log.txt
          xcrun stapler staple release/build/BonBon-*.*.*.dmg | tee -a notarization_log.txt
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - if: matrix.os == 'windows-latest'
        name: latest.yml release for Windows
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file_glob: true
          file: release/build/*-latest.yml
          tag: ${{ github.ref }}

      - if: matrix.os == 'windows-latest'
        name: setup installer for Windows
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file_glob: true
          file: release/build/BonBon Setup *.*.*.exe
          tag: ${{ github.ref }}
